---
- name: Distribute .ovpn files to devices
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Create OpenVPN directory
      file:
        path: /etc/openvpn
        state: directory
        mode: '0755'

    - name: Copy .ovpn files to both possible destinations
      copy:
        src: "/etc/openvpn/client/{{ inventory_hostname }}.ovpn"
        dest: "{{ item }}"
        mode: '0600'
      loop:
        - /etc/openvpn/client.conf
        - /etc/openvpn/client/client.conf

    - name: Check if VPN service is already active
      ansible.builtin.shell: systemctl is-active "openvpn"
      register: vpn_status
      ignore_errors: true

    - name: Stop VPN service if it is active
      ansible.builtin.systemd:
        name: openvpn@client
        state: stopped
      when: vpn_status.stdout not in ["inactive", "unknown"]

    - name: Install OpenVPN if not installed
      apt:
        name: openvpn
        state: present
        update_cache: true

    - name: Enable OpenVPN service on the client
      systemd:
        name: openvpn@client
        enabled: yes
        state: started

    - name: Wait a few seconds for VPN to come up
      wait_for:
        timeout: 10

    - name: Test VPN connectivity (ping VPN server)
      command: ping -c 2 10.8.0.1  # VPN server IP
      register: ping_result
      failed_when: ping_result.rc != 0
