---
- name: Generate .ovpn files and configure static CCD IPs for each host
  hosts: localhost
  gather_facts: no
  vars_files:
    - inventory.ini
  tasks:
    - name: Get host names (all clients)
      set_fact:
        client_names: "{{ groups['local'] }}"

    - name: Ensure generate-ovpn.sh is executable
      ansible.builtin.file:
        path: /srv/developer-server/vpn/generate-ovpn.sh
        mode: '0755'

    - name: Create base client-common.txt file
      ansible.builtin.copy:
        dest: /etc/openvpn/client-common.txt
        content: |
          client
          dev tun
          proto udp
          remote {{ lookup('env', 'VPN_HOST') }} {{ lookup('env', 'VPN_PORT') }}
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          allow-compression no
          verb 3

          # Ignore any "redirect-gateway" pushed by the server.
          pull-filter ignore "redirect-gateway"
          # route 192.168.100.0 255.255.255.0 net_gateway

    - name: Create .ovpn files on the VPS for each client
      ansible.builtin.shell: |
        /srv/developer-server/vpn/generate-ovpn.sh {{ item }}
      args:
        chdir: /etc/openvpn/client
      loop: "{{ client_names }}"
