---
- name: Generar archivos .ovpn y configurar IP estáticas en CCD para cada host
  hosts: localhost
  gather_facts: no
  vars_files:
    - inventory.ini
  tasks:
    - name: Obtener nombres de host (todos los clientes)
      set_fact:
        client_names: "{{ groups['all'] }}"

    - name: Asegurar que generate_ovpn.sh tiene permisos de ejecución
      ansible.builtin.file:
        path: /srv/developer-server/vpn/generate_ovpn.sh
        mode: '0755'

    - name: Crear archivo base client-common.txt
      ansible.builtin.copy:
        dest: /etc/openvpn/client-common.txt
        content: |
          client
          dev tun
          proto udp
          remote tu-dominio-o-ip 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3

    - name: Asegurar que el archivo tls-auth.key existe
      ansible.builtin.copy:
        src: /etc/openvpn/tls-auth.key
        dest: /etc/openvpn/tls-auth.key

    - name: Asegurar que el archivo ca.crt existe
      ansible.builtin.copy:
        src: /etc/openvpn/easy-rsa/easyrsa3/pki/ca.crt
        dest: /etc/openvpn/easy-rsa/pki/ca.crt

    - name: Crear archivos .ovpn en el VPS para cada cliente
      ansible.builtin.shell: |
        /srv/developer-server/vpn/generate_ovpn.sh {{ item }}
      args:
        chdir: /etc/openvpn/client
      loop: "{{ client_names }}"

    - name: Crear directorio CCD si no existe
      ansible.builtin.file:
        path: /etc/openvpn/ccd
        state: directory
        mode: '0755'

    - name: Generar configuraciones estáticas en CCD para cada cliente
      ansible.builtin.template:
        src: /srv/developer-server/vpn/static_client.j2
        dest: "/etc/openvpn/ccd/{{ item }}"
      loop: "{{ client_names }}"
      vars:
        vpn_ip: "{{ hostvars[item].ansible_vpn_host }}"

    - name: Comprimir archivos .ovpn en un tar.gz
      ansible.builtin.archive:
        path:
          - /etc/openvpn/client/*.ovpn
        dest: /etc/openvpn/clients_ovpn.tar.gz
        format: gz
