---
- name: Generate .ovpn files and configure static IPs in CCD for each host
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  vars_files:
    - inventory.ini

  tasks:
    - name: Get host names (all clients)
      set_fact:
        client_names: "{{ groups['all'] }}"

    - name: Validate that VPN_HOST and VPN_PORT environment variables are defined
      ansible.builtin.fail:
        msg: "Error: VPN_HOST and VPN_PORT environment variables must be defined. Please set them before running this playbook."
      when: lookup('env', 'VPN_HOST') == '' or lookup('env', 'VPN_PORT') == ''
      
    - name: Ensure generate-ovpn.sh has execute permissions
      ansible.builtin.file:
        path: /srv/developer-server/vpn/generate-ovpn.sh
        mode: '0755'

    - name: Create base client-common.txt file
      ansible.builtin.copy:
        dest: /etc/openvpn/client-common.txt
        content: |
          client
          dev tun
          proto udp
          remote {{ lookup('env', 'VPN_HOST') }} {{ lookup('env', 'VPN_PORT') }}
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          allow-compression no
          verb 3

          # This line makes any "redirect-gateway" pushed by the server ignored.
          pull-filter ignore "redirect-gateway"
          # route 192.168.100.0 255.255.255.0 net_gateway

    - name: Check for existence of .ovpn files for each client
      ansible.builtin.stat:
        path: "/etc/openvpn/client/{{ item }}.ovpn"
      register: ovpn_stats
      loop: "{{ client_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Generate .ovpn files only for clients that don't have them
      ansible.builtin.shell: |
        /srv/developer-server/vpn/generate-ovpn.sh {{ item.item }}
      args:
        chdir: /etc/openvpn/client
      loop: "{{ ovpn_stats.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: Create CCD directory if it doesn't exist
      ansible.builtin.file:
        path: /etc/openvpn/ccd
        state: directory
        mode: '0755'

    - name: Generate static configurations in CCD for each client
      ansible.builtin.template:
        src: /srv/developer-server/vpn/static_client.j2
        dest: "/etc/openvpn/ccd/{{ item }}"
      loop: "{{ client_names }}"
      vars:
        vpn_ip: "{{ hostvars[item].ansible_vpn_host }}"
      loop_control:
        label: "{{ item }}"

    - name: Compress .ovpn files into a tar.gz
      ansible.builtin.archive:
        path:
          - /etc/openvpn/client/*.ovpn
        dest: /etc/openvpn/clients-ovpn.tar.gz
        format: gz
