apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  namespace: plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: makeplane/plane-live:latest
        ports:
        - containerPort: 3000
        env:
        - name: WEB_URL
          value: https://plane.luis122448.com
        - name: REDIS_URL
          value: redis://redis:6379/0
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: plane
              key: SECRET_KEY
