---
- name: Get Kubernetes Persistent Volume Information
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Get Released PVs
      ansible.builtin.shell:
        cmd: "kubectl get pv --no-headers | grep Released | awk '{print $1}'"
      register: released_pvs
      changed_when: false
    - name: Delete Released PVs from Kubernetes
      ansible.builtin.command:
        cmd: "kubectl delete pv {{ item }}"
      with_items: "{{ released_pvs.stdout_lines }}"
      when: released_pvs.stdout_lines | length > 0
      loop_control:
        label: "Deleting PV {{ item }}"
    - name: Get Bound PVs to protect their data
      ansible.builtin.shell:
        cmd: "kubectl get pv --no-headers | grep Bound | awk '{print $1}'"
      register: bound_pvs
      changed_when: false
    - name: Set bound_pvs_fact
      ansible.builtin.set_fact:
        bound_pvs_list: "{{ bound_pvs.stdout_lines }}"

- name: Soft Clean Kubernetes NFS Persistent Volumes
  hosts: nfs-server
  gather_facts: no
  become: yes
  tasks:
    - name: Find all pvc-* directories on the NFS host
      ansible.builtin.find:
        paths: /mnt/server
        patterns: pvc-*
        file_type: directory
      register: nfs_pvc_dirs
    - name: Identify and delete orphaned directories from the NFS host
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ nfs_pvc_dirs.files }}"
      when: item.path | basename not in hostvars['localhost']['bound_pvs_list']
      loop_control:
        label: "Deleting {{ item.path }} on {{ inventory_hostname }}"