---
- name: Soft Clean Kubernetes NFS Persistent Volumes
  hosts: nfs-server
  gather_facts: no
  become: yes
  tasks:
    - name: Get Released PVs
      ansible.builtin.shell:
        cmd: "kubectl get pv --no-headers | grep Released | awk '{print $1}'"
      register: released_pvs
      changed_when: false
      delegate_to: localhost
      become: yes

    - name: Delete Released PVs from Kubernetes
      ansible.builtin.command:
        cmd: "kubectl delete pv {{ item }}"
      with_items: "{{ released_pvs.stdout_lines }}"
      when: released_pvs.stdout_lines | length > 0
      loop_control:
        label: "Deleting PV {{ item }}"
      delegate_to: localhost
      become: yes

    - name: Get Bound PVs to protect their data
      ansible.builtin.shell:
        cmd: "kubectl get pv --no-headers | grep Bound | awk '{print $1}'"
      register: bound_pvs
      changed_when: false
      delegate_to: localhost
      become: yes

    - name: Find all pvc-* directories on the NFS host
      ansible.builtin.find:
        paths: /mnt/server
        patterns: pvc-*
        file_type: directory
      register: nfs_pvc_dirs

    - name: Identify and delete orphaned directories from the NFS host
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ nfs_pvc_dirs.files }}"
      when: item.path | basename not in bound_pvs.stdout_lines
      loop_control:
        label: "Deleting {{ item.path }} on {{ inventory_hostname }}"
