services:
  plex:
    image: linuxserver/plex:latest
    container_name: plexmediaserver
    network_mode: host # recommended to avoid Bonjour/discovery issues
    environment:
      - PUID=1000 # host User ID (uid)
      - PGID=1000 # host Group ID (gid)
      - TZ=America/Lima
      - VERSION=docker # or 'latest', 'beta', 'public'
    volumes:
      - /mnt/server/plex/config:/config # Plex configuration
      - /mnt/server/video:/data         # main media directory (movies, series, music, etc.)
    restart: unless-stopped
