services:
  plex:
    image: linuxserver/plex:latest
    container_name: plexmediaserver
    network_mode: host # Recomendado para evitar problemas con Bonjour y descubrimiento
    environment:
      - PUID=1000 # Reemplaza con tu User ID (uid) en el servidor
      - PGID=1000 # Reemplaza con tu Group ID (gid) en el servidor
      - TZ=America/Lima # Asegúrate de que tu zona horaria sea correcta
      - VERSION=docker # O 'latest', 'beta', 'public'
    volumes:
      - /mnt/server/plex/config:/config # Directorio para la configuración de Plex
      - /mnt/server/video:/data        # Directorio principal para tus medios (películas, series, música, etc.)
      # Puedes especificar subdirectorios si lo prefieres:
      # - /mnt/server/media/movies:/data/movies
      # - /mnt/server/media/tv:/data/tv
      # - /mnt/server/media/music:/data/music
    restart: unless-stopped