apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-eso-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-eso-credentials
            key: secretAccessKey