apiVersion: v1
kind: Secret
metadata:
  name: aws-eso-credentials
  namespace: external-secrets
type: Opaque
stringData:
  accessKeyID: "YOUR_ACCESS_KEY_ID"
  secretAccessKey: "YOUR_SECRET_ACCESS_KEY"