apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-eso-credentials
            key: accessKeyID
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-eso-credentials
            key: secretAccessKey
            namespace: external-secrets