apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: minio-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "minio-app" # El rol que crearás en Vault
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/minio" # La ruta del secreto en Vault
        vault.hashicorp.com/agent-inject-template-credentials.txt: |
          {{- with secret "secret/data/minio" -}}
          export MINIO_ROOT_USER="{{ .Data.data.username }}"
          export MINIO_ROOT_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: minio-sa
      containers:
        - name: minio
          image: minio/minio:latest
          command: ["/bin/sh", "-c"]
          args:
            - "source /vault/secrets/credentials.txt && /usr/bin/minio server /data --console-address :9001"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
