apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-001
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.100.171
  share: /mnt/server
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
  - actimeo=60