services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"     # DNS
      - "53:53/udp"     # DNS
      - "3000:3000/tcp" # web UI (setup + dashboard)
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
