services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidromelo
    ports:
      - "8003:4533"
    volumes:
      - /mnt/server/music:/music # Replace /path/to/your/music with the actual path to your music library
      - /mnt/server/torrent/downloads/music:/music/torrent # Replace with your torrent download path
      - /mnt/server/navidrome/data:/data        # Persistence for Navidrome database and configuration
    environment:
      - PUID=1000          # Replace with your User ID (uid) on the host server
      - PGID=1000          # Replace with your Group ID (gid) on the host server
      - TZ=America/Lima    # Make sure the time zone is correct
      - SCAN_INTERVAL=1h     # Interval for scanning new files (e.g., every hour)
      # - BASE_URL=/navidrome # If you plan to access via a reverse proxy with a base path
    restart: unless-stopped

networks:
  default:
    name: navidrome_network