services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-app
    network_mode: host
    environment:
      - PUID=1000       # host User ID (uid)
      - PGID=1000       # host Group ID (gid)
      - TZ=America/Lima
      - WEBUI_PORT=8001 # web UI port (must match the port mapping)
    volumes:
      - /mnt/server/torrent/config:/config       # qBittorrent configuration
      - /mnt/server/torrent/downloads:/downloads # download directory
    restart: unless-stopped
