services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8088:8080"
    volumes:
      - open-webui-data:/app/backend/data
    env_file:
      - .env

volumes:
  open-webui-data:
    name: open-webui-data
