---
- name: Install and Configure HAProxy with UFW Rule for Port 6443
  hosts: nas-001 # Specify the IP address 
  become: true
  tasks:
    - name: Update apt cache and install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Allow incoming TCP traffic on port 6443 through UFW
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp
        comment: 'Allow HAProxy traffic on port 6443 (e.g., for Kubernetes API)'

    - name: Allow incoming TCP traffic on port 10257 through UFW
      community.general.ufw:
        rule: allow
        port: '10257'
        proto: tcp
        comment: 'Allow HAProxy traffic on port 10257 (e.g., for Kubernetes API)'

    - name: Allow incoming TCP traffic on port 10259 through UFW
      community.general.ufw:
        rule: allow
        port: '10259'
        proto: tcp
        comment: 'Allow HAProxy traffic on port 10259 (e.g., for Kubernetes API)'

    - name: Allow incoming TCP traffic on port 8404 through UFW
      community.general.ufw:
        rule: allow
        port: '8404'
        proto: tcp
        comment: 'Allow HAProxy traffic on port 8404 (e.g., for custom services)'

    - name: Deploy HAProxy configuration file from template
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Ensure HAProxy service is started and enabled on boot
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      listen: "Restart HAProxy"
      ansible.builtin.service:
        name: haproxy
        state: restarted