---
- name: Instalar HAProxy en VPS
  hosts: 10.8.0.1
  become: true
  tasks:
    - apt:
        name: haproxy
        state: present
    - template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - service:
        name: haproxy
        state: started
        enabled: true