services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - LISTEN=9003
      - KEY=${HUB_KEY}
      - TOKEN=${HUB_TOKEN}
      - HUB_URL=${HUB_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel_agent_data:/var/lib/beszel-agent

volumes:
  beszel_agent_data:
    name: beszel_agent_data
