apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
  namespace: ingress-nginx
data:
  frpc.toml: |
    serverAddr = "VPS"
    serverPort = 7000

    [auth]
    token = "TOKEN"

    [[proxies]]
    name = "nginx-http-passthrough"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 80
    remotePort = 80

    [[proxies]]
    name = "nginx-https-passthrough"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 443
    remotePort = 443

    [[proxies]]
    name = "postgres-passthrough"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 5432
    remotePort = 5432
