services:
  app:
    build: .
    container_name: code-server-lite
    hostname: dev-server
    env_file:
      ./.env
    environment:
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD}
    volumes:
      - ./config:/config
      - ./projects:/home/coder/project
    ports:
      - "8010:8080"
    restart: unless-stopped
