services:
  app:
    build: .
    container_name: code-server-lite
    hostname: dev-server
    env_file:
      ./.env
    user: "root"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PASSWORD: ${PASSWORD}
      SUDO_PASSWORD: ${SUDO_PASSWORD}
      SHELL: /usr/bin/zsh
    volumes:
      - ./config:/config
      - ./projects:/home/coder/project
    ports:
      - "8010:8080"
    restart: unless-stopped