services:
  anki-sync-server:
    image: chrislongros/anki-sync-server-enhanced:latest
    container_name: anki-sync-server
    restart: unless-stopped
    ports:
      - "8004:8080"
    env_file:
      - .env
    environment:
      - SYNC_USER1=${SYNC_USER}:${SYNC_PASSWORD}
      - SYNC_BASE=/data
    volumes:
      - anki_data:/data

volumes:
  anki_data:
    name: anki_data
