---
- name: Instalar Kubernetes (kubeadm, kubelet, kubectl) desde repositorio oficial
  hosts: kubernetes
  become: yes
  vars:
    # Versión de Kubernetes (sin prefijo "v"), se convertirá en "1.32.3-00" para apt
    k8s_version: "1.32.3"
    k8s_apt_version: "{{ k8s_version }}-00"

  tasks:
    - name: Desactivar swap inmediatamente
      ansible.builtin.command: swapoff -a

    - name: Comentar cualquier línea de swap en /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \\1'

    - name: Cargar módulos necesarios en runtime
      ansible.builtin.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Asegurar carga de módulos al arranque
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Ajustar sysctl para Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        owner: root
        group: root
        mode: '0644'

    - name: Aplicar configuraciones de sysctl
      ansible.builtin.command: sysctl --system

    - name: Instalar dependencias para apt via HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Añadir clave GPG del repositorio Kubernetes
      ansible.builtin.apt_key:
        url: https://dl.k8s.io/apt/doc/apt-key.gpg
        state: present

    - name: Añadir repositorio de Kubernetes
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Actualizar cache de apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar kubelet, kubeadm y kubectl en la versión específica
      ansible.builtin.apt:
        name:
          - "kubelet={{ k8s_apt_version }}"
          - "kubeadm={{ k8s_apt_version }}"
          - "kubectl={{ k8s_apt_version }}"
        state: present

    - name: Evitar que kubelet, kubeadm y kubectl se actualicen automáticamente
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    - name: Habilitar y arrancar kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
