---
- name: Configuring kernel parameters for Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Create file /etc/modules-load.d/k8s.conf
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay
        owner: root
        group: root
        mode: '0644'

    - name: Create file /etc/sysctl.d/k8s.conf
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        owner: root
        group: root
        mode: '0644'

    - name: Aplicar los cambios de sysctl
      command: sysctl --system
