---
- name: Update /etc/hosts with all nodes
  hosts: workers, masters
  become: yes
  tasks:
      - name: Update /etc/hosts with all nodes
        ansible.builtin.template:
          src: hosts.j2
          dest: /etc/hosts
          owner: root
          group: root
          mode: "0644"