---
- name: Instalar kubectl binario desde releases oficiales
  hosts: kubernetes
  become: yes
  vars:
    kubectl_version: v1.32.3
  tasks:

    - name: Descargar binario kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
      when: ansible_architecture == "x86_64"

    - name: Descargar binario kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.32.3/bin/linux/arm64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
      when: ansible_architecture == "aarch64"

    - name: Descargar checksum SHA256
      get_url:
        url: "https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kubectl.sha256"
        dest: "/tmp/kubectl.sha256"
        mode: '0644'
      when: ansible_architecture == "x86_64"

    - name: Descargar checksum SHA256
      get_url:
        url: "https://dl.k8s.io/release/v1.32.3/bin/linux/arm64/kubectl.sha256"
        dest: "/tmp/kubectl.sha256"
        mode: '0644'
      when: ansible_architecture == "aarch64"

    - name: Verificar la suma SHA256 del binario kubectl
      ansible.builtin.shell: 'echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check'
      args:
        chdir: /tmp
      register: kubectl_sha256
      changed_when: false
      ignore_errors: yes

    - name: Instalar kubectl en /usr/local/bin
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Verificar instalación de kubectl
      command: kubectl version --client
      register: kubectl_out
      changed_when: false
      failed_when: kubectl_out.rc != 0

    - name: Mostrar salida de kubectl version
      debug:
        var: kubectl_out.stdout
