---
- name: Instalar kubectl y kubeadm desde releases oficiales
  hosts: kubernetes
  become: yes
  vars:
    k8s_version: v1.32.3
  tasks:

    # kubectl
    - name: Descargar binario kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'

    - name: Descargar checksum kubectl SHA256
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/kubectl.sha256"
        dest: "/tmp/kubectl.sha256"
        mode: '0644'

    - name: Verificar SHA256 de kubectl
      ansible.builtin.shell: 'echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check'
      args:
        chdir: /tmp
      register: kubectl_sha256
      changed_when: false
      ignore_errors: yes

    - name: Instalar kubectl en /usr/local/bin
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Verificar instalación de kubectl
      command: kubectl version --client
      register: kubectl_out
      changed_when: false
      failed_when: kubectl_out.rc != 0

    - name: Mostrar salida de kubectl version
      debug:
        var: kubectl_out.stdout

    # Kubeadm
    - name: Descargar binario kubeadm
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/kubeadm"
        dest: "/tmp/kubeadm"
        mode: '0755'

    - name: Descargar checksum kubeadm SHA256
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/kubeadm.sha256"
        dest: "/tmp/kubeadm.sha256"
        mode: '0644'

    - name: Verificar SHA256 de kubeadm
      ansible.builtin.shell: 'echo "$(cat kubeadm.sha256)  kubeadm" | sha256sum --check'
      args:
        chdir: /tmp
      register: kubeadm_sha256
      changed_when: false
      ignore_errors: yes

    - name: Instalar kubeadm en /usr/local/bin
      copy:
        src: /tmp/kubeadm
        dest: /usr/local/bin/kubeadm
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Verificar instalación de kubeadm
      command: kubeadm version
      register: kubeadm_out
      changed_when: false
      failed_when: kubeadm_out.rc != 0

    - name: Mostrar salida de kubeadm version
      debug:
        var: kubeadm_out.stdout
