---
- name: Reset Kubernetes Cluster Configuration
  hosts: workers, masters
  become: yes
  vars:
    cri_socket_path: "unix:///var/run/containerd/containerd.sock"
    admin_kube_config_path: "/root/.kube"

  tasks:
    - name: Reset Kubernetes node with kubeadm
      ansible.builtin.command: "kubeadm reset -f --cri-socket={{ cri_socket_path }}"
      changed_when: true
      ignore_errors: true
      tags: kubeadm_reset

    - name: Remove contents of /etc/kubernetes/manifests directory
      ansible.builtin.shell: "rm -rf /etc/kubernetes/manifests/*"
      changed_when: false
      ignore_errors: true
      tags: cleanup_fs

    - name: Remove contents of /etc/kubernetes directory
      ansible.builtin.shell: "rm -rf /etc/kubernetes/*"
      changed_when: false
      ignore_errors: true
      tags: cleanup_fs

    - name: Remove contents of /var/lib/kubelet directory
      ansible.builtin.shell: "rm -rf /var/lib/kubelet/*"
      changed_when: false
      ignore_errors: true
      tags: cleanup_fs

    - name: Remove contents of /var/lib/etcd directory
      ansible.builtin.shell: "rm -rf /var/lib/etcd/*"
      changed_when: false
      ignore_errors: true
      tags: cleanup_fs

    - name: Remove contents of /etc/cni/net.d directory
      ansible.builtin.shell: "rm -rf /etc/cni/net.d/*"
      changed_when: false
      ignore_errors: true
      tags: cleanup_fs

    - name: Remove admin .kube configuration directory
      ansible.builtin.file:
        path: "{{ admin_kube_config_path }}"
        state: absent
      ignore_errors: true
      tags: cleanup_fs

    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        daemon_reload: yes
      tags: services

    - name: Restart kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes
      ignore_errors: true
      tags: services

    - name: Final reminder
      ansible.builtin.debug:
        msg: "El nodo {{ inventory_hostname }} ha sido reseteado. Kubelet ha sido reiniciado pero podría no estar funcional hasta que se reconfigure (ej. kubeadm init/join)."
      tags: always