---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
  namespace: ingress-nginx
data:
  frpc.toml: |
    serverAddr = "3.144.88.23"
    serverPort = 7000

    [auth]
    token = "RmKj9TzXcP2qVbLnHdFwG7sYm@a$E!r"

    [[proxies]]
    name = "nginx-ingress-http"
    type = "http"
    localIP = "192.168.100.240"
    localPort = 80
    customDomains = ["test.luis122448.com"]

    [[proxies]] # Otro proxy
    name = "nginx-ingress-https"
    type = "https"
    localIP = "192.168.100.240"
    localPort = 443
    customDomains = ["test.luis122448.com"]