--- 
- name: Bootstrap Raspberry Pi nodes for SSH access
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    ssh_key_file: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

  tasks:
    - name: Install OpenSSH server on Debian/Ubuntu
      apt:
        name: openssh-server
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install OpenSSH server on Archlinux
      pacman:
        name: openssh
        state: present
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Ensure SSH service is started and enabled (Debian/Ubuntu)
      service:
        name: ssh
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure SSH service is started and enabled (Archlinux/RedHat)
      service:
        name: sshd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Archlinux" or ansible_facts['os_family'] == "RedHat"

    - name: Ensure SSH key exists
      stat:
        path: "{{ ssh_key_file }}"
      delegate_to: localhost
      register: ssh_key_status

    - name: Generate SSH key if not exists
      command: ssh-keygen -t rsa -b 2048 -f {{ lookup('env','HOME') }}/.ssh/id_rsa -N ""
      delegate_to: localhost
      when: not ssh_key_status.stat.exists

    - name: Read public SSH key
      slurp:
        src: "{{ ssh_key_file }}"
      delegate_to: localhost
      register: public_key_raw

    - name: Set authorized key on remote nodes
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key_raw.content | b64decode }}"

    - name: Accept host key automatically (add to known_hosts)
      known_hosts:
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        name: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        key: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars[inventory_hostname]['ansible_host']) }}"

