- name: Shutdown servers
  hosts: all
  gather_facts: no
  become: yes
  any_errors_fatal: false
  tasks:
    - name: Shutdown servers
      command: poweroff
      become_user: root
      become_method: sudo
      ignore_errors: yes
      async: 0