---
- name: Install and configure UFW
  hosts: all
  become: true
  vars:
    ufw_open_port: 8080
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install UFW if not present
      apt:
        name: ufw
        state: present

    - name: Allow SSH (port 22)
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow TCP traffic on port {{ ufw_open_port }}
      ufw:
        rule: allow
        port: "{{ ufw_open_port }}"
        proto: tcp

    - name: Allow UDP traffic on port {{ ufw_open_port }}
      ufw:
        rule: allow
        port: "{{ ufw_open_port }}"
        proto: udp

    - name: Enable UFW (if not enabled)
      ufw:
        state: enabled