apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-external-svc
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8008
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: onlyoffice-external-svc-slice
  namespace: default
  labels:
    kubernetes.io/service-name: onlyoffice-external-svc
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8008
endpoints:
  - addresses:
      - "192.168.100.161"
